name: metrics_app_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.1
  - numpy=1.26.3
  - pandas=2.1.4
  - plotly=5.24.1
  - boto3=1.34.150
  - weasyprint=62.3
  - streamlit=1.38.0
  - openpyxl=3.1.2
  - cairo
  - pango
  - jpeg
  - gdk-pixbuf
  - pip=23.3.1
  - pip:
    - numpy==1.26.3
    - pandas==2.1.4
    - plotly==5.24.1
    - boto3==1.34.150
    - weasyprint==62.3
    - streamlit==1.39.0
    - openpyxl==3.1.2
