name: unilabs_app

channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python==3.12.1
  - samtools==1.19.2
  - numpy==1.26.3
  - pandas==2.1.4
  - plotly==5.24.1
  - pip==23.3.1
  - git
  - pip:
    - boto3==1.34.150
    - weasyprint==62.3
    - streamlit==1.38.0